(() => {
  const system=document.querySelector('#system'); if(!system)return;
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const clock=document.querySelector('#hls-clock');
  const updateClock=()=>{clock.textContent=new Intl.DateTimeFormat('pt-BR',{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(new Date())};updateClock();setInterval(updateClock,1000);
  let countersPlayed=false;
  const animateCounters=()=>{if(countersPlayed)return;countersPlayed=true;document.querySelectorAll('[data-system-count]').forEach(el=>{const target=Number(el.dataset.systemCount),start=performance.now();const tick=now=>{const p=Math.min(1,(now-start)/1100);el.textContent=Math.round(target*(1-Math.pow(1-p,3)));if(p<1)requestAnimationFrame(tick)};reduced?el.textContent=target:requestAnimationFrame(tick)})};
  const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(!entry.isIntersecting)return;entry.target.classList.add('is-visible');if(entry.target.classList.contains('command-dashboard'))animateCounters();observer.unobserve(entry.target)}),{threshold:.12,rootMargin:'0px 0px -7%'});
  document.querySelectorAll('.system-reveal').forEach(item=>reduced?item.classList.add('is-visible'):observer.observe(item));if(reduced)animateCounters();
  const records=[...document.querySelectorAll('.mission-record')],detail=document.querySelector('#mission-detail');
  document.querySelectorAll('[data-mission-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-mission-filter]').forEach(item=>item.classList.toggle('active',item===button));records.forEach(record=>record.hidden=button.dataset.missionFilter!=='all'&&record.dataset.type!==button.dataset.missionFilter)}));
  records.forEach(record=>record.addEventListener('click',()=>{records.forEach(item=>item.classList.toggle('active',item===record));detail.innerHTML=`<span>${record.dataset.code} // ACESSO PARCIAL</span><strong>${record.querySelector('b').textContent}</strong><p>${record.querySelector('p').textContent} Dados de agentes, clientes e datas permanecem classificados.</p>`}));
  const forum={command:[['JC','Jack Connor','COMANDO','Operação 148 permanece suspensa até a confirmação de Alice. Nenhuma entrada antes da autorização.','#bbd64a'],['AM','Alice Myers','ADMINISTRAÇÃO','Cliente verificado. Contrato em revisão jurídica e financeira.','#e3a63c'],['MC','Mark Connor','TÁTICA','Plano de extração atualizado no canal de operações.','#4e9cc7']],operations:[['MC','Mark Connor','TÁTICA','Equipe de campo: revisar rota secundária antes das 22:00.','#4e9cc7'],['DJ','Dimitri','INTERVENÇÃO','Veículo e equipamento pesado prontos no setor 05.','#c94a3e'],['LK','Luke','ROTAS','Três saídas confirmadas. A rota norte permanece limpa.','#53b68a']],intel:[['NM','Naomi','INTELIGÊNCIA','O alvo mudou de identidade duas vezes nas últimas 48 horas.','#d95d6f'],['CH','Clhoe','RECONHECIMENTO','Observação visual confirmada. Nenhum civil no perímetro imediato.','#bd6ed2'],['BT','Brian Taylor','RASTREAMENTO','O padrão não é aleatório. Coordenadas enviadas ao comando.','#b5a071']],medical:[['AM','Alice Myers','COORDENAÇÃO MÉDICA','Enfermaria abastecida. Protocolo de retorno atualizado.','#e3a63c'],['HL','Hellen','INFILTRAÇÃO','Sem ferimentos. Identidade de cobertura preservada.','#d18450']]};
  const feed=document.querySelector('#forum-feed');const render=channel=>{feed.innerHTML=forum[channel].map((m,i)=>`<article class="forum-message" style="--msg-color:${m[4]};animation-delay:${i*90}ms"><span class="forum-avatar">${m[0]}</span><div><header><strong>${m[1]}</strong><span>${m[2]} · AGORA</span></header><p>${m[3]}</p></div></article>`).join('')};document.querySelectorAll('[data-channel]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-channel]').forEach(item=>item.classList.toggle('active',item===button));render(button.dataset.channel)}));render('command');
  const form=document.querySelector('#contract-form'),result=document.querySelector('#contract-result'),brief=form.elements.brief,count=document.querySelector('#brief-count');brief.addEventListener('input',()=>count.textContent=brief.value.length);
  form.addEventListener('submit',event=>{event.preventDefault();const data=Object.fromEntries(new FormData(form)),protocol=`HLS-${Date.now().toString(36).slice(-6).toUpperCase()}`;result.querySelector('#contract-protocol').textContent=protocol;result.querySelectorAll('[data-contract]').forEach(field=>field.textContent=data[field.dataset.contract]||'—');try{localStorage.setItem('hls-last-protocol',JSON.stringify({protocol,createdAt:new Date().toISOString(),type:data.type,risk:data.risk}))}catch(error){}result.classList.add('show')});
  result.querySelector('.contract-result-close').addEventListener('click',()=>result.classList.remove('show'));result.querySelector('#copy-contract').addEventListener('click',async event=>{const protocol=result.querySelector('#contract-protocol').textContent;try{await navigator.clipboard.writeText(protocol);event.currentTarget.textContent='PROTOCOLO COPIADO'}catch(error){event.currentTarget.textContent=protocol}});
})();
